collections:
  projects:
    output: true
    permalink: /project/:name
    order:
      - wise.html
      - farasa.html
      - qmdis.html
      - natasy.html
      - buzzdiggr.html
      - taps.html
      - arabagent.html
      - its.html

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"